version: '3.9'

services:
  db:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api-1:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    container_name: api
    env_file:
      - .env.prod
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  api-2:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    container_name: api
    env_file:
      - .env.prod
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
  nginx:
     build:
       context: ./nginx
       dockerfile: Dockerfile
     ports:
       - "80:80"
       - "443:443"
     depends_on:
       - api-1
       - api-2

volumes:
  postgres-data:
  redis-data: